src/GoRegister/Areas/Admin/Controllers/ThemesController.cs
using GoRegister.Areas.Admin.ViewModels;
using GoRegister.ApplicationCore.Domain.ProjectThemes.Models;
using GoRegister.ApplicationCore.Domain.ProjectThemes.Services;
using GoRegister.ApplicationCore.Framework.Domain;
using GoRegister.ApplicationCore.Framework.Notifications;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Amazon.Runtime;
using Amazon.S3;
using System.IO;
using Amazon.S3.Transfer;
using GoRegister.ApplicationCore.Domain.Settings.Services;
using MediatR;
using GoRegister.ApplicationCore.Domain.ProjectThemes.Queries;
using GoRegister.ApplicationCore.Domain.ProjectThemes.Commands;
using GoRegister.Filters;

namespace GoRegister.Areas.Admin.Controllers
{
    public class ThemesController : ProjectAdminControllerBase
    {
        private readonly INotifier _notifier;
        private readonly IProjectThemeService _projectThemeService;
        private readonly IConfiguration _configuration;
        private readonly IProjectSettingsAccessor _projectSettings;
        private readonly IMediator _mediator;

        public ThemesController(INotifier notifier, IProjectThemeService projectThemeService, IConfiguration configuration, IProjectSettingsAccessor projectSettings, IMediator mediator)
        {
            _notifier = notifier;
            _projectThemeService = projectThemeService;
            _configuration = configuration;
            _projectSettings = projectSettings;
            _mediator = mediator;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _mediator.Send(new ProjectThemeEditQuery());
            return View(model);
        }

        [HttpPost, ModelStateValidation]
        public async Task<IActionResult> SaveTheme(ProjectThemeEditCommand model)
        {
            var result = await _mediator.Send(model);
            if(!result)
            {
                _notifier.Error("Something went wrong while saving your theme, please try again");
                return View(nameof(Index), model);
            }

            _notifier.Success("Theme saved successfully");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<int> PostTheme([FromForm] ProjectThemeModel model, IFormFile file)
        {
            if (file != null)
            {
                //Call logo upload function
                Guid logoGuid = Guid.NewGuid();
                model.ThemeUniqueId = logoGuid;

                model.File = file;

                //var result = await _projectThemeService.ProjectThemeUpload(model);

                //model.LogoUrl = Convert.ToString(result);
            }

            var newThemeId = _projectThemeService.SaveProjectThemeAsync(model);

            return newThemeId.Result;
        }

        

        [HttpGet]
        public async Task<IActionResult> GetTheme(int Id)
        {
            var model = await _projectThemeService.GetTheme(Id);

            model.LayoutOptions = _projectThemeService.GetLayoutOptions();

            return Json(model);
        }

        public IActionResult ThemeHistory(int id)
        {
            var list = _projectThemeService.GetProjectThemeByProjectIdAll(id);

            return View(list);
        }

        [HttpGet]
        public IActionResult EditThemeId(int id)
        {
            var model = _projectThemeService.GetProjectThemeById(id);

            return View("Index", model);
        }

    }
}

src/GoRegister/Controllers/ThemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoRegister.ApplicationCore.Domain.ProjectThemes.Services;
using GoRegister.ApplicationCore.Domain.Settings.Services;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace GoRegister.Controllers
{
    public class ThemeController : Controller
    {
        private readonly IProjectThemeService _projectThemeService;
        private readonly IProjectSettingsAccessor _projectSettingsAccessor;

        public ThemeController (IProjectThemeService projectThemeService, IProjectSettingsAccessor projectSettingsAccessor)
        {
            _projectThemeService = projectThemeService;
            _projectSettingsAccessor = projectSettingsAccessor;
        }


        public async Task<IActionResult> OverrideCss(int id)
        {
            var projectTheme = await _projectThemeService.GetProjectThemeByProjectIdAsync(id);

            var overrideCss = "";

            if (projectTheme != null)
            {
                overrideCss = projectTheme.OverrideCss;
            }

            return Content(overrideCss, "text/css");
        }

        public async Task<IActionResult> ThemeCss(int id)
        {
            var projectTheme = await _projectThemeService.GetProjectThemeByProjectIdAsync(id);

            var themeCss = "";

            if (projectTheme != null)
            {
                themeCss = projectTheme.ThemeCss;
            }

            return Content(themeCss, "text/css");
        }

        public async Task<IActionResult> ThemeVariables(int id)
        {
            var projectTheme = await _projectThemeService.GetProjectThemeByProjectIdAsync(id);

            var themeVariables = "";

            if (projectTheme != null)
            {
                themeVariables = ":root {" + projectTheme.ThemeVariables + "}";
            }

            return Content(themeVariables, "text/css");
        }

        public async Task<IActionResult> PreviewOverrideCss(int id)
        {
            var projectTheme = _projectThemeService.GetProjectThemeById(id);

            return Content(projectTheme.OverrideCss, "text/css");
        }

        public async Task<IActionResult> PreviewThemeCss(int id)
        {
            var projectTheme =  _projectThemeService.GetProjectThemeById(id);

            return Content(projectTheme.ThemeCss, "text/css");
        }

        public async Task<IActionResult> PreviewThemeVariables(int id)
        {
            var projectTheme =  _projectThemeService.GetProjectThemeById(id);

            var themeVariables = ":root {" + projectTheme.ThemeVariables + "}";

            return Content(themeVariables, "text/css");
        }

        public async Task<IActionResult> HeaderScripts(int id)
        {
            var projectTheme = await _projectSettingsAccessor.GetTheme();

            var headerScripts = "";

            if (projectTheme != null)
            {
                headerScripts = projectTheme.HeadScripts;
            }

            return Content(headerScripts, "text/javascript");
        }

        public async Task<IActionResult> FooterScripts(int id)
        {
            var projectTheme = await _projectSettingsAccessor.GetTheme();

            var footerScripts = "";

            if (projectTheme != null)
            {
                footerScripts = projectTheme.FooterScripts;
            }

            //return Content(footerScripts, "text/javascript");
            return Content(HtmlEncoder.Default.Encode(footerScripts), "text/javascript"); //GOR-371
        }
    }
}

src/GoRegister/Areas/Admin/Views/Themes/Detail.cshtml
@model GoRegister.Areas.Admin.ViewModels.ThemeDetailViewModel


<a-proj class="btn btn-primary" asp-action="Activate" asp-controller="Themes" asp-area="Admin" asp-route-theme="@Model.Theme">Set Current</a-proj>
<div class="">
    @*@Html.Raw(Model.Content)*@
    @(Model.Content)
</div>

src/GoRegister/Areas/Admin/Views/Themes/Index.cshtml
@*@model GoRegister.ApplicationCore.Domain.ProjectThemes.Commands.ProjectThemeEditCommand
<link href="/assets/vendor/codemirror/lib/codemirror.css" rel="stylesheet" />

<div id="page-config" data-page="theme-edit"></div>

<form-proj asp-action="SaveTheme" asp-controller="Themes" autocomplete="off" enctype="multipart/form-data">

    <div class="d-flex justify-content-between align-items-center border-bottom">
        <h1>Edit Theme</h1>
        <input type="submit" value="Save" class="btn btn-success" />
    </div>
    @if (Model.ProjectIsTemplate)
    {
        <div class="form-group">
            <label asp-for="LayoutName" class="control-label"></label>
            <select asp-for="LayoutName" asp-items="Model.LayoutOptions" class="form-control"></select>
            <span asp-validation-for="LayoutName" class="text-danger"></span>
        </div>
    }
    <h3 class="border-bottom pt-4">Upload Logo</h3>
    <input type="file" name="file" id="imgUpload" class="form-control-file" asp-for="File" />
    <br />
    @if (Model.LogoUrl != string.Empty && Model.LogoUrl != null)
    {
        <img src=@Model.LogoUrl class="img-fluid" alt="Responsive image" width="200" height="200" />
    }


    <h3 class="border-bottom pt-4">Theme CSS</h3>
    <div class="from-group">
        <textarea asp-for="ThemeCss" data-codemirror="css"></textarea>
    </div>
    <h3 class="border-bottom pt-4">Theme Header Scripts</h3>
    <div class="from-group">
        <textarea asp-for="HeadScripts" data-codemirror="javascript"></textarea>
    </div>
    <h3 class="border-bottom pt-4">Theme Footer Scripts</h3>
    <div>
        <textarea asp-for="FooterScripts" data-codemirror="javascript"></textarea>
    </div>

    <h3 class="border-bottom pt-4">Header Html</h3>
    <div class="from-group">
        <textarea asp-for="HeaderHtml" class="js-html-editor"></textarea>
    </div>
    <h3 class="border-bottom pt-4">Footer Html</h3>
    <div>
        <textarea asp-for="FooterHtml" class="js-html-editor"></textarea>
    </div>

    <div class="d-flex justify-content-end align-items-center border-top mt-3 pt-3 pb-3">
        <input type="submit" value="Save" class="btn btn-success" />
    </div>
</form-proj>

@section libscripts {
    <script src="/assets/vendor/codemirror/lib/codemirror.js"></script>
    <script src="/assets/vendor/codemirror/mode/css/css.js"></script>   
}*@

src/GoRegister/Areas/Admin/Views/Themes/ThemeHistory.cshtml
@model IEnumerable<GoRegister.ApplicationCore.Domain.ProjectThemes.Models.ProjectThemeListItemModel>
@{
    ViewData["Title"] = "ThemePreviousVersion";
}

<h1>Previous Versions</h1>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Theme Name
                </th>
                <th>
                    Date Saved
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.DateUpdated
                    </td>
                    <td>
                        <a asp-action="EditThemeId" asp-route-id="@item.Id">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>